import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount } from 'wagmi';

import { Account } from '../components/Account';

export default function Home() {
  const { isConnected } = useAccount();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>its-our-house-house-house</div>
      <ConnectButton />
      {isConnected && <Account />}
    </>
  );
}
