import { FC, ReactNode } from 'react';
import NextHead from 'next/head';

import Navigation from '../Navigation';
import Footer from '../Footer';

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <>
      <NextHead>
        <title>My wagmi + RainbowKit App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </NextHead>
      <div className="flex flex-col items-center justify-between w-screen min-h-screen">
        <Navigation />
        <div className="flex-grow w-full px-5 max-w-7xl xl:px-0">
          {children}
        </div>
        <Footer />
      </div>
    </>
  );
};

export default RootLayout;
