import { FC, ReactNode } from 'react';
import NextHead from 'next/head';

import Navigation from '../Navigation';
import Footer from '../Footer';
import { useTheme } from '../../hooks/useTheme';
import Hamburger from '../Hamburger';

import FontWrapper from './Fonts/FontWrapper';

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  const theme = useTheme();

  const displayNav = theme === 'sleek';
  return (
    <>
      <NextHead>
        <title>My DAO</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </NextHead>

      <FontWrapper>
        <div
          className={`flex flex-col justify-between items-center w-screen min-h-screen ${theme}`}
        >
          {displayNav ? <Navigation /> : <Hamburger />}
          <div className="flex-grow px-5 py-5 max-w-7xl xl:px-0">
            {children}
          </div>
          <Footer />
        </div>
      </FontWrapper>
    </>
  );
};

export default RootLayout;
